sudo: required
env:
- GHCVER=8.2.1
- GHCVER=8.4.1
- GHCVER=head

script:
- export HLINT_ARGUMENTS=src
- export UNIPLATE_VERBOSE=-1
- curl -sL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
